services:
  - type: web
    name: fishnet-api
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: fishnet-db
          property: connectionString
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: fishnet-db
    databaseName: fishnet
    user: fishnet_user
    plan: free
